from .dataset_config import *

DataConfig = {
    "PRETRAINING": [CC3M_595K, COCO_CAP, COCO_REG, COCO_REC],

    "FINETUNING": [CONV_VideoChatGPT, VCG_HUMAN, VCG_PLUS_112K, CAPTION_VIDEOCHAT, CLASSIFICATION_K710, CLASSIFICATION_SSV2, CONV_VideoChat1, REASONING_NExTQA, REASONING_CLEVRER_QA, REASONING_CLEVRER_MC, VQA_WEBVID_QA],

    "VCGBench_FINETUNING": [CONV_VideoChatGPT, VCG_HUMAN, VCG_PLUS_112K, CAPTION_VIDEOCHAT, CONV_VideoChat1, VQA_WEBVID_QA],
    "MVBench_FINETUNING": [CLASSIFICATION_K710, CLASSIFICATION_SSV2, CONV_VideoChatGPT, REASONING_NExTQA, REASONING_CLEVRER_QA, REASONING_CLEVRER_MC, VQA_WEBVID_QA],
    "MVBench_capvqa_sub": [CLASSIFICATION_K710_vqa_sub, CLASSIFICATION_SSV2_vqa_sub, CONV_VideoChatGPT_vqa_sub, REASONING_NExTQA_vqa_sub, REASONING_CLEVRER_QA_vqa_sub, REASONING_CLEVRER_MC_vqa_sub, VQA_WEBVID_QA_vqa_sub],
    "MVBench_capvqa": [CLASSIFICATION_K710_vqa, CLASSIFICATION_SSV2_vqa, CONV_VideoChatGPT_vqa, REASONING_NExTQA_vqa, REASONING_CLEVRER_QA_vqa, REASONING_CLEVRER_MC_vqa, VQA_WEBVID_QA_vqa],
}
